{
    'name': 'Hospital Management',
    'version': '1.0.0',
    'category': 'Hospital',
    'author': 'Odoo Learn',
    'sequence': 1,
    'summary': 'Hospital Management System',
    'description': """Hospital Management System""",
    'depends': ['base', 'mail', 'product'],
    'data': [
        'security/ir.model.access.csv',
        'data/patient_tag_data.xml',
        'data/patient.tag.csv',
        'data/sequence_data.xml',
        'views/menu.xml',
        'views/patient_tag_views.xml',
        'views/patient_views.xml',
        'views/female_patient_view.xml',
        'wizard/cancel_appointment_views.xml',
        'views/appointment.xml',
        'views/operation_view.xml',
        'views/odoo_playground_view.xml',
        'views/res_config_settings_views.xml',

    ],
    'demo': [],
    'application': True,
    'installable': True,
    'auto_install': False,
}